### ISSUE TITLE
Jump Servers

### ISSUE THREAD

**Issue by cramphal** [grelleum/youtube-network-automation#5]
Hello Greg,

I am a complete novice at scripting and greatly appreciate your video!  I've managed to automate a portion of my work with amazing success, however some of my devices are only reachable through a jump server (ssh proxy).  To my understanding Netmiko supports this action, but I really couldn't find any solution on the internet that worked.  I need to be able to connect to devices by jumping through an ssh connection to another linux box. would you be able to provide me any insight?  TIA.  

-Collin

**Comment by grelleum** [comment]
Have you looked at this page, which is from Kirk Byers who created Netmiko?
https://pynet.twb-tech.com/blog/automation/netmiko-proxy.html
If that does not work for you, then you would need to be more specific as to what is not working - are you getting specific errors?

Let me know how that turns out.
- Greg

**Comment by cramphal** [comment]
Thanks for getting back to be Greg.  here is a sample of my script without the jumpserver.  Is there a way of adding the jumpserver without reading from a separate file? I've tried Kirk's method but I'm not to great with passing dictionaries.  

#!/usr/bin/env python

from __future__ import absolute_import, division, print_function

import netmiko
import paramiko
import socket
import json

devices = '''

24.106.131.234
24.106.68.198

''' .strip().splitlines()

device_type = 'cisco_ios'
username = 'user'
password = 'password'
secret = 'secret'

for device in devices:
    try:
        print('_'*79)
        print('Connecting to router ', device)
        connection = netmiko.ConnectHandler(ip=device, device_type=device_type,
                                        username=username, password=password, secret=secret,)
        connection.enable()
        print(connection.send_command('show running-config | include hostname'))
        connection.send_config_set('username user privilege 15 secret new_password')
        connection.send_config_set('enable secret new_secret')
        print(connection.send_command('wr mem'), device)
        connection.disconnect()
    except netmiko.ssh_exception.NetMikoTimeoutException:
        print('ERROR - Connection Timeout or Refused to ', device)
    except netmiko.ssh_exception.NetMikoAuthenticationException:
        print('ERROR - Password Failure', device)
    except ValueError:
        print('ERROR - Failed privilege mode', device)
    except paramiko.ssh_exception.SSHException:
        print('ERROR - Connection Abort', device)
    except socket.error:
        print('ERROR - Socket error', device)
