### ISSUE TITLE
Merging Answers and Questions

### ISSUE THREAD

**Issue by newscriptkid** [grelleum/youtube-network-automation#7]
Hi Greg,

Hope all is well,

I was doing a project where I have a text file with questions with multiple choices and the answer field is blank and another text file with answer key. What I am trying to achieve is to use the answers from the answer key file and add it to the question file. See below my attempt:

The question file has the following data (I have only listed 5 questions, there are over 1000 questions)

1. How often do you eat supper?
A) last night
B) the day after tomorrow
C) every night
D) Sunday 
ANSWER:
 
2. How about a cup of coffee?
A) Yes I do.
B) Yes, please
C) No, please
D) No, I don't. 
ANSWER:
 
3. What can we do in a bank?
A) mail a letter
B) send a package
C) open an account
D) buy a suit 
ANSWER:
 
4. It's four fifteen. What time is it?
A) 4:15 hours
B) quarter to four
C) 15:15 hours
D) a quarter past four 
ANSWER:
 
5. He has a scholarship. What does he have?
A) a government support
B) a class in the morning
C) a ship for traveling
D) a shower 
ANSWER:

The Answer file has the following data:

Answer Key:
1.C
2.B
3.C
4.D
5.A

below is the code i've been trying but struggling:

'''
original_list =[]
answer_list =[]

final_with_answer = []

with open('question.docx', 'rb') as f:
    original_doc = Document(f)

with open('Answer-key.docx', 'rb') as f:
    answer_doc = Document(f)

for each in original_doc.paragraphs:
    original_list.append(each.text)

for each in answer_doc.paragraphs:
    answer_list.append(each.text)

m = 0
for n, each in enumerate(original_list):
    if '.' in each:
       
        final_with_answer.append(original_list[n][int(len(str(n)) + 1):].strip())
        final_with_answer.append('A' + original_list[n + 2][1:])
        final_with_answer.append('B' + original_list[n + 3][1:])
        final_with_answer.append('C' + original_list[n + 4][1:])
        final_with_answer.append('D' + original_list[n + 5][1:])
        final_with_answer.append( 'ANSWER'+ answer_list[m] + '\n')

with open('final_with_answer.txt', 'w') as printfile:
    for line in final_with_answer:
        printfile.write(line + '\n')
'''
Any help is appreciated.

Thanks

**Comment by grelleum** [comment]
It is unclear from your code what "Document" is.  I would assume it is some class or function that will read a file handle and parse that information.

Ultimately, what you are looking for is something called zip, which can take two sequences combine them:

```
>>> questions = [ "who", "what", "when", "where", "how", "why" ]
>>> answers = [ "me", "wrote code", "yesterday", "at home", "using the computer", "why not?" ]
>>>
>>> for q, a in zip(questions, answers):
...     print(f"{q}? {a}")
...
who? me
what? wrote code
when? yesterday
where? at home
how? using the computer
why? why not?
>>>
```
